version: '3.1'
services:
  mongodb:
    image: mongo:3.4.20
    environment:
      MONGO_INITDB_DATABASE: aram-all-time-table
    ports:
      - 27017:27017
    volumes:
      - "./.docker/mongodb/db:/data/db"
    command: --smallfiles
    networks:
      - lol

  mongoAdmin:
    image: mrvautin/adminmongo:latest
    links:
      - mongodb:mongodb
    ports:
      - 1234:1234
    environment:
      - HOST=0.0.0.0
      - PORT=1234
      - CONN_NAME=whatever
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=aram-all-time-table
    networks:
      - lol

networks:
  lol: